services:
  - type: web
    name: hrms-lite-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: sh entrypoint.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://placeholder.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: hrms-lite-db
          property: connectionString

databases:
  - name: hrms-lite-db
    databaseName: hrms_db
    user: hrms_user
    plan: free
